### ISSUE TITLE
Unable to connect

### ISSUE THREAD

**Issue by envy2000** [Hornwitser/discord_bridge#1]
Discord Bridge is unable to log in to discord. I have double checked the bot token works (I'm currently using my test bot, which has its token used in other places), and other programs are able to log into the discord bot fine, implying the issue is with the discord bridge.

The logs related to discord bridge when starting the controller are as such:

[info] discord_bridge: Logging in to Discord
[error] discord_bridge: Error logging in to Discord, bridge is offline:
Error: Used disallowed intents
    at WebSocketShard.onClose (C:\Servers\Factorio\Factoriocluster\node_modules\@discordjs\ws\src\ws\WebSocketShard.ts:805:13)
    at WebSocket.connection.onclose (C:\Servers\Factorio\Factoriocluster\node_modules\@discordjs\ws\src\ws\WebSocketShard.ts:206:14)
    at callListener (C:\Servers\Factorio\Factoriocluster\node_modules\ws\lib\event-target.js:290:14)
    at WebSocket.onClose (C:\Servers\Factorio\Factoriocluster\node_modules\ws\lib\event-target.js:220:9)
    at WebSocket.emit (node:events:518:28)
    at WebSocket.emitClose (C:\Servers\Factorio\Factoriocluster\node_modules\ws\lib\websocket.js:265:10)
    at TLSSocket.socketOnClose (C:\Servers\Factorio\Factoriocluster\node_modules\ws\lib\websocket.js:1289:15)
    at TLSSocket.emit (node:events:530:35)
    at node:net:337:12
    at TCP.done (node:_tls_wrap:657:7)
[info] Loaded plugin discord_bridge

**Comment by Hornwitser** [comment]
The Message Content Intent needs to be enabled in Discord's dashboard for the bot

**Comment by envy2000** [comment]
Oh, My bad.
Thank you for the help, it seems to be operational now.
